mali-userland: use anonymous method instead of COMPATIBLE_MACHINE
This makes it works for all machines that set 'mali450' without editing this recipe.

And as a bonus it gives a better error message:

	[koen@thinkpad build-rpb]$ MACHINE=dragonboard-410c bitbake mali450-userland
	Parsing recipes: 100% |###############################################################################| Time: 00:01:59
	Parsing of 2364 .bb files complete (0 cached, 2364 parsed). 2994 targets, 191 skipped, 0 masked, 0 errors.
	ERROR: Nothing PROVIDES 'mali450-userland'
	ERROR: mali450-userland was skipped: mali450-userland-r6p0 ONLY supports machines with a MALI iGPU

Signed-off-by: Koen Kooi <koen.kooi@linaro.org>