u-boot-juno: add patch to avoid to build libfdt.so
Stolen from https://patchwork.openembedded.org/patch/141629/

When swig is present and python-dev is missing, it's causing a build
failure:
ERROR: oe_runmake failed
| tools/libfdt_wrap.c:147:21: fatal error: Python.h: No such file or directory
|  # include <Python.h>
|                      ^
| compilation terminated.

Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>