grub: fix NoneType error when the recipe is used on other boards than HiKey
If the recipe is used by other boards than Hikey, it triggers an
exception because the CMDLINE_ROOT_* variables aren't always set:
Exception: TypeError: argument of type 'NoneType' is not iterable

Make sure we ship default cfg files, even if they are HiKey specific.
Rework the function to set GRUB_CFG: set a default value to grub_cfg, add
a test to check if our variable isn't None.

Layer that override the recipe can just have a SRC_URI_append with their
own cfg files and invoke do_deploy_prepend() to set GRUB_CFG as they wish.

Reported-by: Ricardo Salveti <ricardo.salveti@linaro.org>
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>